const $=s=>document.querySelector(s),state={height:null,heightInput:null,image:null,decodedImage:null,analysis:null,result:null};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function requireHeight(){const input=$('#calibrationHeight'),value=Number(input.value);try{if(!input.validity.valid)throw new Error();state.heightInput=window.tailorScanCalibration.createHeightInput(value)}catch{toast('Enter a valid height first.');input.focus();return false}state.height=state.heightInput.height_inches;return true}
function showScreen(id){document.querySelectorAll('.screen').forEach(screen=>screen.classList.toggle('active',screen.id===id));$('#restartButton').hidden=id==='home';window.scrollTo({top:0,behavior:'smooth'})}
function readPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('The selected photo could not be read.'));reader.readAsDataURL(file)})}
$('#photoFile').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{state.image=await readPhoto(file);state.analysis=null;state.result=null;const preview=$('#photoPreview');preview.src=state.image;preview.hidden=false;$('#photoMessage').hidden=true;$('#processButton').disabled=false;$('#processingStatus').className='processing-status ready';$('#processingStatus').textContent='Photo ready. Tap “Trace body outline”.'}catch(error){$('#processingStatus').className='processing-status error';$('#processingStatus').textContent=error.message}});
function debugArtifacts(){return window.tailorScanDebug.createDebugArtifacts(state.decodedImage,state.analysis.segmentationMaskRef,state.analysis.rawPose,state.result.stage2,state.heightInput,state.result.stage3,state.result.stage3b,state.result.stage3c,state.result.stage3d,state.result.stage3e,state.result.stage3f)}
function drawResult(){const canvas=$('#resultOutline'),context=canvas.getContext('2d'),overlay=debugArtifacts().stage3f_landmark_overlay;canvas.width=overlay.width;canvas.height=overlay.height;context.drawImage(overlay,0,0)}
function showDebugArtifacts(){const container=$('#debugDownloads');container.innerHTML='';Object.entries(debugArtifacts()).forEach(([name,value])=>{if(!value)return;const link=document.createElement('a');if(name.endsWith('debug_data')){link.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const stage=name.match(/^stage(\d+[a-z]?)/)?.[1];link.download=stage?`tailor-scan-stage${stage}-debug.json`:'tailor-scan-stage2-debug.json'}else{link.href=value.toDataURL('image/png');link.download=`tailor-scan-${name.replaceAll('_','-')}.png`}link.textContent=`Download ${name.replaceAll('_',' ')}`;container.appendChild(link)})}
async function processPhoto(){const button=$('#processButton'),status=$('#processingStatus');button.disabled=true;button.textContent='Processing photo…';status.className='processing-status working';status.textContent='Loading the body model and tracing the person. Keep this page open; the first run can take up to a minute.';try{if(!window.tailorScanVision?.createProvider)throw new Error('The on-device vision module did not load. Check the internet connection and reload.');state.decodedImage=await window.tailorScanImages.loadImage(state.image);const provider=state.provider||await window.tailorScanVision.createProvider();state.provider=provider;state.analysis=await provider.analyzeFrame({id:'front',angle:0,image:state.image});const stage2=window.tailorScanStage2.resolve({rawPose:state.analysis.rawPose,personMask:state.analysis.segmentationMaskRef,segmentation:state.analysis.segmentation,heightInput:state.heightInput});const stage3=window.tailorScanStage3.resolve({rawPose:state.analysis.rawPose,personMask:state.analysis.segmentationMaskRef,stage2});const stage3b=window.tailorScanStage3B.resolve({rawPose:state.analysis.rawPose,stage2,stage3});const stage3c=window.tailorScanStage3C.resolve({rawPose:state.analysis.rawPose,stage2,stage3,stage3b});const stage3d=window.tailorScanStage3D.resolve({rawPose:state.analysis.rawPose,personMask:state.analysis.segmentationMaskRef,stage2,stage3c});const stage3e=window.tailorScanStage3E.resolve({rawPose:state.analysis.rawPose,personMask:state.analysis.segmentationMaskRef,stage2,stage3c,stage3d});const stage3f=window.tailorScanStage3F.resolve({rawPose:state.analysis.rawPose,personMask:state.analysis.segmentationMaskRef,stage2,stage3d,stage3e});state.result={heightInput:state.heightInput,rawPose:state.analysis.rawPose,tailoringLandmarks:stage3f.resolvedLandmarks,personMask:state.analysis.segmentationMaskRef,stage2,stage3,stage3b,stage3c,stage3d,stage3e,stage3f};drawResult();showDebugArtifacts();$('#outlineStatus').textContent=`Stage 3F refined the neck-to-shoulder transition while preserving Stage 3E acromions. ${stage3f.warnings.length?`Warnings: ${stage3f.warnings.join(', ')}.`:'No quality warnings.'} No tailoring measurements were calculated.`;status.className='processing-status success';status.textContent='Stage 3F neck refinement completed.';showScreen('outline')}catch(error){console.error(error);status.className='processing-status error';status.textContent=`Processing failed: ${error.message}`;button.disabled=false;button.textContent='Try tracing again'}}
$('#processButton').addEventListener('click',processPhoto);
document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.go;if(id==='capture'&&!requireHeight())return;showScreen(id)}));$('#restartButton').addEventListener('click',()=>showScreen('home'));window.tailorScan=Object.freeze({getResult:()=>state.result});
