(function setupLiveExperiment(){
  const $=selector=>document.querySelector(selector),video=$('#liveVideo'),overlay=$('#liveOverlay'),context=overlay.getContext('2d'),capture=document.createElement('canvas');
  let stream=null,session=null,provider=null,running=false,inferenceBusy=false,timer=null,currentAnalysis=null,lastScore=null,finalResult=null;
  const config=()=>({frameRate:Number($('#liveFrameRate').value)||7,maxFrames:18,maxObservationsPerLandmark:24,minimumRetainedFrames:8,minimumObservations:5,minimumStability:.62,minimumDurationMs:2500,timeoutMs:12000,startTime:performance.now()});
  async function openCamera(){stopTracks();const facingMode=$('#liveCameraFacing').value;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:720},height:{ideal:1280}},audio:false});video.srcObject=stream;await video.play();overlay.width=video.videoWidth||720;overlay.height=video.videoHeight||1280;capture.width=overlay.width;capture.height=overlay.height;}
  function stopTracks(){stream?.getTracks().forEach(track=>track.stop());stream=null;}
  function draw(){if(!video.videoWidth){if(running)requestAnimationFrame(draw);return}context.clearRect(0,0,overlay.width,overlay.height);if(currentAnalysis?.rawPose){context.fillStyle='#64d2ff';for(const name of window.tailorScanLiveL1.REQUIRED){const point=currentAnalysis.rawPose.landmarks[name];if(!point)continue;context.beginPath();context.arc(point.x*overlay.width,point.y*overlay.height,3,0,Math.PI*2);context.fill()}}if(session){context.strokeStyle='rgba(255,159,10,.45)';context.fillStyle='#30d158';for(const name of window.tailorScanLiveL1.REQUIRED){const stable=window.tailorScanLiveL1.stabilizeLandmark(session.landmarks[name].observations,session.config),recent=stable.observations.slice(-6);for(const observation of recent){context.beginPath();context.arc(observation.x_image_norm*overlay.width,observation.y_image_norm*overlay.height,observation.outlier?5:2,0,Math.PI*2);observation.outlier?context.stroke():context.fill()}if(stable.stabilized_position&&stable.observations.length){const nearest=stable.observations.reduce((best,item)=>Math.hypot(item.x_body_norm-stable.stabilized_position.x_body_norm,item.y_body_norm-stable.stabilized_position.y_body_norm)<best.distance?{item,distance:Math.hypot(item.x_body_norm-stable.stabilized_position.x_body_norm,item.y_body_norm-stable.stabilized_position.y_body_norm)}:best,{item:null,distance:Infinity}).item;if(nearest){context.strokeStyle='#30d158';context.lineWidth=2;context.beginPath();context.arc(nearest.x_image_norm*overlay.width,nearest.y_image_norm*overlay.height,7,0,Math.PI*2);context.stroke()}}}}if(running)requestAnimationFrame(draw)}
  function updateProgress(){if(!session)return;const progress=window.tailorScanLiveL1.progress(session);$('#livePerson').textContent=progress.person_visible;$('#livePose').textContent=`${Math.round(progress.pose_quality*100)}%`;$('#liveStable').textContent=`${progress.stable_landmarks} / ${progress.total_landmarks}`;$('#liveConfidence').textContent=`${Math.round(progress.capture_confidence*100)}%`;$('#liveFrameScore').textContent=lastScore?`Current frame quality ${Math.round(lastScore.overall_frame_score*100)}%`:'Gathering evidence…'}
  async function analyze(){if(!running)return;if(inferenceBusy){schedule();return}if(performance.now()-session.startTime>=session.config.timeoutMs){finish(false);return}inferenceBusy=true;window.tailorScanLiveL1.markFrameSeen(session);try{capture.getContext('2d').drawImage(video,0,0,capture.width,capture.height);const image=capture.toDataURL('image/jpeg',.82);provider=provider||await window.tailorScanVision.createProvider();const timestamp=performance.now(),analysis=await provider.analyzeFrame({id:`live-${session.framesAnalyzed}`,angle:0,image}),stage2=resolveStage2(analysis);currentAnalysis=analysis;lastScore=window.tailorScanLiveL1.addFrame(session,{timestamp,rawPose:analysis.rawPose,stage2,quality:analysis.quality,segmentation:analysis.segmentation});updateProgress();const interim=window.tailorScanLiveL1.summarize(session,timestamp);if(interim.session.status==='sufficient'){finish(false);return}}catch(error){window.tailorScanLiveL1.ignoreFrame(session,performance.now(),classifyInferenceError(error));updateProgress()}finally{inferenceBusy=false}schedule()}
  function resolveStage2(analysis){try{return window.tailorScanStage2.resolve({rawPose:analysis.rawPose,personMask:analysis.segmentationMaskRef,segmentation:analysis.segmentation,heightInput:null})}catch{return null}}
  function classifyInferenceError(error){const message=String(error?.message||error);return message.includes('pose')?'POSE_NOT_AVAILABLE':message.includes('silhouette')?'SEGMENTATION_NOT_AVAILABLE':'FRAME_ANALYSIS_UNAVAILABLE'}
  function schedule(){if(running){clearTimeout(timer);timer=setTimeout(analyze,Math.max(80,1000/session.config.frameRate))}}
  async function start(){try{$('#liveStart').disabled=true;$('#liveStatus').className='processing-status working';$('#liveStatus').textContent='Opening camera and gathering useful frames…';await openCamera();session=window.tailorScanLiveL1.createSession(config());running=true;finalResult=null;currentAnalysis=null;lastScore=null;$('#liveStop').disabled=false;$('#liveDownload').hidden=true;requestAnimationFrame(draw);analyze()}catch(error){running=false;stopTracks();$('#liveStart').disabled=false;$('#liveStatus').className='processing-status error';$('#liveStatus').textContent=`Camera unavailable: ${error.message}`}}
  function finish(requestedFallback){if(!session)return;running=false;clearTimeout(timer);stopTracks();finalResult=window.tailorScanLiveL1.summarize(session,performance.now(),requestedFallback);$('#liveStart').disabled=false;$('#liveStop').disabled=true;$('#liveStatus').className=`processing-status ${finalResult.session.status==='sufficient'?'success':'ready'}`;$('#liveStatus').textContent=finalResult.session.status==='sufficient'?'Live evidence is sufficient for this experiment. No measurements were calculated.':finalResult.session.status==='fallback_to_photo_mode'?`Live evidence was insufficient: ${finalResult.warnings[0]||'use photo mode'}.`:'Capture stopped before enough evidence was gathered.';const link=$('#liveDownload');link.href=URL.createObjectURL(new Blob([JSON.stringify(finalResult,null,2)],{type:'application/json'}));link.download='tailor-scan-live-stageL1-debug.json';link.hidden=false}
  $('#liveStart').addEventListener('click',start);$('#liveStop').addEventListener('click',()=>finish(false));$('#liveFallback').addEventListener('click',()=>{if(session)finish(true);showPhotoMode()});$('#liveCameraFacing').addEventListener('change',()=>{if(running)openCamera().catch(()=>finish(true))});
  $('#liveEntry').addEventListener('click',()=>{document.querySelectorAll('.screen').forEach(screen=>screen.classList.toggle('active',screen.id==='live'));$('#restartButton').hidden=false});
  $('#restartButton').addEventListener('click',()=>{if(running)finish(false);else stopTracks()});
  function showPhotoMode(){document.querySelectorAll('.screen').forEach(screen=>screen.classList.toggle('active',screen.id==='capture'));}
  window.addEventListener('beforeunload',stopTracks);
})();
