(function exposeStage3F(root) {
  const clamp = value => Math.max(0, Math.min(1, value));
  const mean = values => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
  const median = values => { if (!values.length) return 0; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.floor(sorted.length / 2)]; };
  const category = value => value === null ? 'unresolved' : value >= .75 ? 'high' : value >= .5 ? 'moderate' : 'low';
  const axisGeometry = axis => { const dx = axis.bottom.x - axis.top.x, dy = axis.bottom.y - axis.top.y, length = Math.hypot(dx, dy); return { ux: dx / length, uy: dy / length, px: -dy / length, py: dx / length, length }; };
  const project = (point, axis, geometry) => (point.x - axis.top.x) * geometry.ux + (point.y - axis.top.y) * geometry.uy;
  const at = (axis, geometry, bodyPosition, lateral = 0) => ({ x: axis.top.x + geometry.ux * bodyPosition + geometry.px * lateral, y: axis.top.y + geometry.uy * bodyPosition + geometry.py * lateral });
  const landmarkPoint = landmark => landmark ? { x: landmark.x_px, y: landmark.y_px, confidence: landmark.confidence } : null;

  function buildNeckProfile({ personMask, component, rawPose, stage2, stage3d, stage3e }) {
    const axis = stage2.bodyAxis, geometry = axisGeometry(axis), leftShoulder = rawPose.landmarks.left_shoulder, rightShoulder = rawPose.landmarks.right_shoulder;
    const leftAcromion = landmarkPoint(stage3e.resolvedLandmarks.left_acromion), rightAcromion = landmarkPoint(stage3e.resolvedLandmarks.right_acromion);
    if (!leftShoulder || !rightShoulder || !leftAcromion || !rightAcromion) return { raw_profile: [], normalized_profile: [], warnings: ['NECK_PROFILE_REQUIRED_EVIDENCE_MISSING'] };
    const shoulderPoints = [{ x: leftShoulder.x * rawPose.image_width, y: leftShoulder.y * rawPose.image_height }, { x: rightShoulder.x * rawPose.image_width, y: rightShoulder.y * rawPose.image_height }];
    const shoulderLevel = mean(shoulderPoints.map(point => project(point, axis, geometry))), acromionLevel = mean([project(leftAcromion, axis, geometry), project(rightAcromion, axis, geometry)]), acromionSpan = Math.hypot(leftAcromion.x - rightAcromion.x, leftAcromion.y - rightAcromion.y);
    const priorSamples = stage3d.neckAnalysis?.width_profile || [], priorStart = priorSamples[0] ? project({ x: root.tailorScanTorsoProfile.axisX(axis, priorSamples[0].body_y), y: priorSamples[0].body_y }, axis, geometry) : shoulderLevel - acromionSpan * .65;
    const start = Math.min(priorStart, shoulderLevel - acromionSpan * .18), end = Math.max(shoulderLevel, acromionLevel) + acromionSpan * .08, maskScaleX = rawPose.image_width / component.width, maskScaleY = rawPose.image_height / component.height, sampleSpacing = Math.max(maskScaleX, maskScaleY), lateralLimit = acromionSpan * .62, raw = [];
    for (let bodyPosition = start; bodyPosition <= end; bodyPosition += sampleSpacing) {
      const center = at(axis, geometry, bodyPosition), steps = Math.ceil(lateralLimit / sampleSpacing), occupied = [];
      for (let offset = -steps; offset <= steps; offset++) {
        const lateral = offset * sampleSpacing, point = at(axis, geometry, bodyPosition, lateral), mx = Math.round(point.x / maskScaleX), my = Math.round(point.y / maskScaleY);
        if (mx >= 0 && mx < component.width && my >= 0 && my < component.height && component.data[my * component.width + mx]) occupied.push({ offset, lateral, point, confidence: personMask.data[my * personMask.width + mx] || 0 });
      }
      const centerIndex = occupied.findIndex(item => item.offset >= 0), centerOccupied = occupied.find(item => item.offset === 0);
      if (!centerOccupied || centerIndex < 0) continue;
      let leftIndex = occupied.indexOf(centerOccupied), rightIndex = leftIndex;
      while (leftIndex > 0 && occupied[leftIndex].offset - occupied[leftIndex - 1].offset === 1) leftIndex--;
      while (rightIndex + 1 < occupied.length && occupied[rightIndex + 1].offset - occupied[rightIndex].offset === 1) rightIndex++;
      const left = occupied[leftIndex], right = occupied[rightIndex], width = right.lateral - left.lateral + sampleSpacing, confidence = mean(occupied.slice(leftIndex, rightIndex + 1).map(item => item.confidence));
      raw.push({ index: raw.length, body_axis_position: bodyPosition, body_axis_norm: bodyPosition / geometry.length, center, left_boundary: left.point, right_boundary: right.point, left_distance: Math.abs(left.lateral), right_distance: Math.abs(right.lateral), neck_width: width, bilateral_contour_confidence: clamp(1 - Math.abs(Math.abs(left.lateral) - Math.abs(right.lateral)) / Math.max(width, 1)), segmentation_confidence: confidence });
    }
    const radius = Math.max(1, Math.round(raw.length * .035)), smoothed = raw.map((_, index) => mean(raw.slice(Math.max(0, index - radius), index + radius + 1).map(sample => sample.neck_width)));
    const normalized = raw.map((sample, index) => {
      const before = smoothed[Math.max(0, index - 1)], after = smoothed[Math.min(smoothed.length - 1, index + 1)], spacing = raw[Math.min(raw.length - 1, index + 1)].body_axis_position - raw[Math.max(0, index - 1)].body_axis_position || sampleSpacing;
      const derivative = (after - before) / spacing, normalizedDerivative = derivative * acromionSpan / Math.max(smoothed[index], 1), previousDerivative = index ? (smoothed[index] - smoothed[index - 1]) / sampleSpacing : 0, nextDerivative = index + 1 < smoothed.length ? (smoothed[index + 1] - smoothed[index]) / sampleSpacing : 0;
      const leftDerivative = index ? (sample.left_distance - raw[index - 1].left_distance) / sampleSpacing : 0, rightDerivative = index ? (sample.right_distance - raw[index - 1].right_distance) / sampleSpacing : 0;
      return { ...sample, smoothed_width: smoothed[index], first_derivative: derivative, normalized_first_derivative: normalizedDerivative, normalized_second_derivative: (nextDerivative - previousDerivative) * acromionSpan / Math.max(smoothed[index], 1), left_expansion_rate: leftDerivative, right_expansion_rate: rightDerivative, local_continuity: index ? clamp(1 - Math.abs(smoothed[index] - smoothed[index - 1]) / Math.max(acromionSpan * .25, 1)) : sample.bilateral_contour_confidence, width_to_acromion_span: smoothed[index] / Math.max(acromionSpan, 1) };
    });
    return { raw_profile: raw, normalized_profile: normalized, sample_spacing: sampleSpacing, smoothing_radius: radius, acromion_span: acromionSpan, raw_shoulder_span: Math.hypot((leftShoulder.x - rightShoulder.x) * rawPose.image_width, (leftShoulder.y - rightShoulder.y) * rawPose.image_height), body_axis_height: geometry.length, search_region: { start_body_axis_position: start, end_body_axis_position: end }, warnings: [] };
  }

  function analyzeProfile(profile) {
    const samples = profile.normalized_profile || [];
    if (samples.length < 9) return { neck_shaft_zone: null, anatomical_expansion_zone: null, shoulder_entry_zone: null, candidate_regions: [], selected_transition_region: null, rejection_reasons: ['NECK_PROFILE_INSUFFICIENT'] };
    const window = Math.max(3, Math.round(samples.length * .09)), shaftCandidates = [];
    for (let start = 0; start + window < samples.length; start++) {
      const zone = samples.slice(start, start + window), widths = zone.map(sample => sample.smoothed_width), average = mean(widths), variation = Math.sqrt(mean(widths.map(width => (width - average) ** 2))) / Math.max(average, 1), continuity = mean(zone.map(sample => sample.local_continuity)), bilateral = mean(zone.map(sample => sample.bilateral_contour_confidence)), narrowness = clamp(1 - average / Math.max(profile.acromion_span * .72, 1)), stability = clamp(1 - variation / .14), score = .38 * stability + .25 * continuity + .2 * bilateral + .17 * narrowness;
      shaftCandidates.push({ start_index: start, end_index: start + window - 1, width: average, stability, continuity, bilateral, narrowness, score });
    }
    const shaft = shaftCandidates.filter(candidate => candidate.narrowness > .15).sort((a, b) => b.score - a.score || b.end_index - a.end_index)[0];
    if (!shaft || shaft.score < .48) return { neck_shaft_zone: null, anatomical_expansion_zone: null, shoulder_entry_zone: null, candidate_regions: shaftCandidates, selected_transition_region: null, rejection_reasons: ['NECK_SHAFT_UNSUPPORTED'] };
    const postShaft = samples.slice(shaft.end_index + 1), positiveBaseline = median(postShaft.map(sample => Math.max(0, sample.normalized_first_derivative)).filter(value => value > 0)) || .01, entryCandidates = postShaft.map(sample => {
      const bilateralParticipation = sample.left_expansion_rate > 0 && sample.right_expansion_rate > 0 ? 1 : sample.left_expansion_rate > 0 || sample.right_expansion_rate > 0 ? .45 : 0, jumpContrast = clamp(sample.normalized_first_derivative / Math.max(positiveBaseline * 3, .01)), shoulderScale = clamp((sample.width_to_acromion_span - .34) / .38), acceleration = clamp(Math.max(0, sample.normalized_second_derivative) / 4), score = .42 * jumpContrast + .27 * shoulderScale + .18 * bilateralParticipation + .13 * acceleration;
      return { index: sample.index, score, jump_contrast: jumpContrast, shoulder_scale: shoulderScale, bilateral_participation: bilateralParticipation, acceleration };
    });
    const persistentEntry = entryCandidates.find(candidate => candidate.score >= .52 && entryCandidates.filter(other => other.index >= candidate.index && other.index <= candidate.index + window).filter(other => other.score >= .34).length >= Math.max(2, Math.floor(window * .55)));
    const entry = persistentEntry ? { start_index: persistentEntry.index, end_index: Math.min(samples.length - 1, persistentEntry.index + window - 1), ...persistentEntry } : null;
    const expansionStart = shaft.end_index, expansionEnd = entry ? entry.start_index : Math.min(samples.length - 1, shaft.end_index + window * 2), expansionSamples = samples.slice(expansionStart, expansionEnd + 1), widening = expansionSamples.filter(sample => sample.normalized_first_derivative > 0), expansionPersistence = widening.length / Math.max(expansionSamples.length, 1), directionStability = widening.length > 1 ? clamp(1 - Math.sqrt(mean(widening.map(sample => (sample.normalized_first_derivative - mean(widening.map(item => item.normalized_first_derivative))) ** 2))) / Math.max(mean(widening.map(sample => sample.normalized_first_derivative)), .01)) : 0, bilateralParticipation = mean(expansionSamples.map(sample => sample.left_expansion_rate > 0 && sample.right_expansion_rate > 0 ? 1 : sample.left_expansion_rate > 0 || sample.right_expansion_rate > 0 ? .45 : 0));
    const expansion = expansionSamples.length >= 2 ? { start_index: expansionStart, end_index: expansionEnd, persistence: expansionPersistence, direction_stability: directionStability, bilateral_participation: bilateralParticipation, normalized_expansion_rate: mean(expansionSamples.map(sample => Math.max(0, sample.normalized_first_derivative))), confidence: clamp(.45 * expansionPersistence + .3 * bilateralParticipation + .25 * directionStability) } : null;
    const transitionStart = Math.max(shaft.end_index, (entry?.start_index ?? expansionEnd) - Math.max(2, Math.round(window * .75))), transitionEnd = entry?.start_index ?? expansionEnd, selected = samples.slice(transitionStart, transitionEnd + 1);
    const selectedRegion = expansion && expansion.persistence >= .35 ? { start_index: transitionStart, end_index: transitionEnd, center_index: Math.round((transitionStart + transitionEnd) / 2), support: clamp(.45 * expansion.confidence + .3 * shaft.score + .25 * (entry?.score ?? .3)) } : null;
    const rejectionReasons = []; if (!entry) rejectionReasons.push('SHOULDER_ENTRY_UNRESOLVED'); if (!expansion || expansion.persistence < .35) rejectionReasons.push('GRADUAL_EXPANSION_UNSUPPORTED'); if (!selectedRegion) rejectionReasons.push('NECK_TRANSITION_REGION_UNRESOLVED');
    return { neck_shaft_zone: shaft, neck_shaft_width: shaft.width, neck_shaft_stability: shaft.stability, neck_shaft_confidence: shaft.score, anatomical_expansion_zone: expansion, shoulder_entry_zone: entry, shoulder_dominated_expansion: entry, candidate_regions: shaftCandidates, selected_transition_region: selectedRegion, rejection_reasons: rejectionReasons };
  }

  function resolveNeck({ profile, analysis, stage2, stage3e }) {
    const samples = profile.normalized_profile || [], region = analysis.selected_transition_region, leftAcromion = landmarkPoint(stage3e.resolvedLandmarks.left_acromion), rightAcromion = landmarkPoint(stage3e.resolvedLandmarks.right_acromion), axis = stage2.bodyAxis, geometry = axisGeometry(axis);
    if (!region || !leftAcromion || !rightAcromion) return unresolved(profile, analysis, ['NECK_TRANSITION_UNRESOLVED']);
    const regionSamples = samples.slice(region.start_index, region.end_index + 1), negativeIndex = selectSideIndex(regionSamples, 'left_expansion_rate'), positiveIndex = selectSideIndex(regionSamples, 'right_expansion_rate'), negativeSample = samples[negativeIndex], positiveSample = samples[positiveIndex], negativePoint = { ...negativeSample.left_boundary }, positivePoint = { ...positiveSample.right_boundary }, provisionalLevel = mean([negativeSample.body_axis_position, positiveSample.body_axis_position]), provisionalBase = at(axis, geometry, provisionalLevel), acLeftSign = Math.sign((leftAcromion.x - provisionalBase.x) * geometry.px + (leftAcromion.y - provisionalBase.y) * geometry.py), leftUsesNegative = acLeftSign < 0, leftSample = leftUsesNegative ? negativeSample : positiveSample, rightSample = leftUsesNegative ? positiveSample : negativeSample, left = leftUsesNegative ? negativePoint : positivePoint, right = leftUsesNegative ? positivePoint : negativePoint, centerLevel = mean([leftSample.body_axis_position, rightSample.body_axis_position]), base = at(axis, geometry, centerLevel), neckWidth = Math.hypot(left.x - right.x, left.y - right.y), acromionSpan = profile.acromion_span;
    const centerLeft = at(axis, geometry, leftSample.body_axis_position), centerRight = at(axis, geometry, rightSample.body_axis_position), leftLateral = (left.x - centerLeft.x) * geometry.px + (left.y - centerLeft.y) * geometry.py, rightLateral = (right.x - centerRight.x) * geometry.px + (right.y - centerRight.y) * geometry.py, acLeftLateral = (leftAcromion.x - base.x) * geometry.px + (leftAcromion.y - base.y) * geometry.py, acRightLateral = (rightAcromion.x - base.x) * geometry.px + (rightAcromion.y - base.y) * geometry.py;
    const sideOrder = Math.sign(leftLateral) === Math.sign(acLeftLateral) && Math.sign(rightLateral) === Math.sign(acRightLateral) && Math.sign(leftLateral) !== Math.sign(rightLateral), medial = Math.abs(leftLateral) < Math.abs(acLeftLateral) && Math.abs(rightLateral) < Math.abs(acRightLateral), widthPlausibility = clamp(1 - Math.max(0, neckWidth / Math.max(acromionSpan, 1) - .72) / .28), levelAgreement = clamp(1 - Math.abs(leftSample.body_axis_position - rightSample.body_axis_position) / Math.max(acromionSpan * .18, 1)), bilateral = mean(regionSamples.map(sample => sample.bilateral_contour_confidence)), continuity = mean(regionSamples.map(sample => sample.local_continuity)), segmentation = mean(regionSamples.map(sample => sample.segmentation_confidence)), acromionSupport = mean([leftAcromion.confidence, rightAcromion.confidence]), shaftEvidence = analysis.neck_shaft_confidence || 0, gradual = analysis.anatomical_expansion_zone?.confidence || 0, entrySeparation = analysis.shoulder_entry_zone ? clamp(analysis.shoulder_entry_zone.jump_contrast * .65 + analysis.shoulder_entry_zone.shoulder_scale * .35) : .2, axisStability = clamp(stage2.bodyAxis.confidence ?? 1);
    const components = { neck_shaft_evidence: shaftEvidence, gradual_expansion_persistence: gradual, bilateral_agreement: bilateral * levelAgreement, shoulder_entry_separation: entrySeparation, contour_continuity: continuity, segmentation_quality: segmentation, neck_width_plausibility: widthPlausibility, accepted_acromion_support: acromionSupport, body_axis_stability: axisStability };
    const confidence = clamp(.16 * components.neck_shaft_evidence + .16 * components.gradual_expansion_persistence + .13 * components.bilateral_agreement + .12 * components.shoulder_entry_separation + .11 * components.contour_continuity + .09 * components.segmentation_quality + .09 * components.neck_width_plausibility + .08 * components.accepted_acromion_support + .06 * components.body_axis_stability);
    const hardReasons = []; if (!sideOrder) hardReasons.push('NECK_SIDE_ORDER_INVALID'); if (!medial) hardReasons.push('NECK_LATERAL_TO_ACROMION'); if (widthPlausibility < .35) hardReasons.push('NECK_WIDTH_IMPLAUSIBLE'); if (bilateral < .3 || segmentation < .3) hardReasons.push('NECK_SEGMENTATION_INCOMPLETE'); if (!analysis.anatomical_expansion_zone || analysis.anatomical_expansion_zone.persistence < .35) hardReasons.push('NECK_SUSTAINED_PROFILE_MISSING'); if (!analysis.shoulder_entry_zone) hardReasons.push('NECK_SHOULDER_ENTRY_UNSUPPORTED');
    const acceptanceState = hardReasons.length || confidence < .38 ? 'unresolved' : confidence >= .66 ? 'accepted' : 'low_confidence_accepted', measurementReady = acceptanceState === 'accepted' && confidence >= .75;
    if (acceptanceState === 'unresolved') return unresolved(profile, analysis, hardReasons.length ? hardReasons : ['NECK_CONFIDENCE_INSUFFICIENT'], components, confidence);
    left.confidence = confidence; right.confidence = confidence; base.confidence = confidence;
    return { left, right, base, analysis: { raw_profile: profile.raw_profile, normalized_profile: samples, neck_shaft_zone: analysis.neck_shaft_zone, neck_shaft_width: analysis.neck_shaft_width, neck_shaft_stability: analysis.neck_shaft_stability, neck_shaft_confidence: analysis.neck_shaft_confidence, anatomical_expansion_zone: analysis.anatomical_expansion_zone, shoulder_entry_zone: analysis.shoulder_entry_zone, candidate_regions: analysis.candidate_regions, selected_transition_region: region, left_transition: left, right_transition: right, neck_base: base, transition_line: { left, right }, body_axis_projected_level: centerLevel, neck_width_at_transition: neckWidth, confidence_components: components, final_confidence: confidence, confidence: { numeric: confidence, category: category(confidence) }, acceptance_state: acceptanceState, landmark_acceptance_state: acceptanceState, measurement_ready: measurementReady, rejection_reasons: [], warnings: acceptanceState === 'low_confidence_accepted' ? ['NECK_LOW_CONFIDENCE_ACCEPTED'] : [], generalization_diagnostics: profileDiagnostics(profile) } };
  }

  function selectSideIndex(samples, key) { const positive = samples.filter(sample => sample[key] > 0); if (!positive.length) return samples[Math.floor(samples.length / 2)].index; const strongest = Math.max(...positive.map(sample => sample[key])); const stable = positive.filter(sample => sample[key] >= strongest * .55); return stable[Math.floor(stable.length / 2)].index; }
  function profileDiagnostics(profile) { return { sample_spacing_px: profile.sample_spacing, acromion_span_px: profile.acromion_span, raw_shoulder_span_px: profile.raw_shoulder_span, body_axis_height_px: profile.body_axis_height, scale_policy: 'derivatives normalized by local neck width, acromion span, body-axis distance, and profile sample spacing', known_height_used_for_placement: false }; }
  function unresolved(profile, analysis, reasons, components = {}, confidence = 0) { return { left: null, right: null, base: null, analysis: { raw_profile: profile.raw_profile || [], normalized_profile: profile.normalized_profile || [], neck_shaft_zone: analysis.neck_shaft_zone || null, anatomical_expansion_zone: analysis.anatomical_expansion_zone || null, shoulder_entry_zone: analysis.shoulder_entry_zone || null, candidate_regions: analysis.candidate_regions || [], selected_transition_region: analysis.selected_transition_region || null, left_transition: null, right_transition: null, neck_base: null, confidence_components: components, final_confidence: confidence, confidence: { numeric: 0, category: 'unresolved' }, acceptance_state: 'unresolved', landmark_acceptance_state: 'unresolved', measurement_ready: false, rejection_reasons: reasons, warnings: ['NECK_TRANSITION_UNRESOLVED'], generalization_diagnostics: profileDiagnostics(profile) } }; }

  function resolve({ rawPose, personMask, stage2, stage3d, stage3e }) {
    const component = root.tailorScanStage2.dominantComponent(personMask), profile = buildNeckProfile({ personMask, component, rawPose, stage2, stage3d, stage3e }), profileAnalysis = analyzeProfile(profile), neck = resolveNeck({ profile, analysis: profileAnalysis, stage2, stage3e }), values = { ...stage3e.resolvedLandmarks }, normalization = root.tailorScanStage2.createNormalization(stage2.bodyAxis);
    const make = (name, point, source) => { if (!point) return null; const normalized = normalization.point(point, rawPose.image_width, rawPose.image_height); return root.tailorScanLandmarks.createLandmark({ name, x_px: point.x, y_px: point.y, x_norm: normalized.x_image_norm, y_norm: normalized.y_image_norm, ...normalized, confidence: point.confidence, source, diagnostics: neck.analysis, frame_id: rawPose.frame_id, view_id: rawPose.view_id }); };
    values.left_neck_transition = make('left_neck_transition', neck.left, 'silhouette'); values.right_neck_transition = make('right_neck_transition', neck.right, 'silhouette'); values.neck_base = make('neck_base', neck.base, 'derived');
    const readiness = { ...stage3e.measurementLandmarkReadiness, neck_based_measurements_ready: neck.analysis.measurement_ready };
    const preservedWarnings = (stage3e.warnings || []).filter(warning => !warning.includes('NECK'));
    return { resolvedLandmarks: root.tailorScanLandmarks.createTailoringLandmarks(values), shoulderAnalysis: stage3e.shoulderAnalysis, neckAnalysisStage3F: neck.analysis, neckAnalysisStage3E: stage3e.neckAnalysis, bilateralShoulderDiagnostics: stage3e.bilateralShoulderDiagnostics, measurementLandmarkReadiness: readiness, generalizationDiagnostics: { ...stage3e.generalizationDiagnostics, neck_stage3f: profileDiagnostics(profile) }, warnings: [...new Set([...preservedWarnings, ...(neck.analysis.warnings || [])])] };
  }

  root.tailorScanStage3F = Object.freeze({ buildNeckProfile, analyzeProfile, resolveNeck, resolve, category });
})(typeof window === 'undefined' ? globalThis : window);
