const assert=require('node:assert/strict'),fs=require('node:fs'),test=require('node:test'),vm=require('node:vm');
function api(){const context={};for(const file of ['landmark-model.js','stage2-resolver.js','live-stage-l1.js'])vm.runInNewContext(fs.readFileSync(file,'utf8'),context);return context.tailorScanLiveL1}
const names=['left_shoulder','right_shoulder','left_elbow','right_elbow','left_wrist','right_wrist','left_hip','right_hip','left_knee','right_knee','left_ankle','right_ankle'];
function frame(offset=0,{visibility=.9,width=200,height=400,missing=[],coverage=.88,segmentation=.9,timestamp=0}={}){const base={left_shoulder:[.4,.25],right_shoulder:[.6,.25],left_elbow:[.35,.4],right_elbow:[.65,.4],left_wrist:[.32,.55],right_wrist:[.68,.55],left_hip:[.44,.55],right_hip:[.56,.55],left_knee:[.43,.73],right_knee:[.57,.73],left_ankle:[.42,.92],right_ankle:[.58,.92]},landmarks={};for(const [name,[x,y]] of Object.entries(base))landmarks[name]=missing.includes(name)?null:{x:x+offset,y:y+offset*.2,visibility,presence:visibility};return{timestamp,rawPose:{image_width:width,image_height:height,landmarks},quality:{segmentationQuality:segmentation},segmentation:{boundingBox:{height:coverage},confidence:segmentation}}}
function fill(session,count=10,options={}){const live=api();for(let i=0;i<count;i++){live.markFrameSeen(session);live.addFrame(session,frame((i%3-1)*.001,{...options,timestamp:i*200}))}return live}

test('good frames are retained while weak frames are silently ignored',()=>{const live=api(),session=live.createSession({startTime:0});live.markFrameSeen(session);const good=live.addFrame(session,frame(0,{timestamp:100}));live.markFrameSeen(session);const weak=live.addFrame(session,frame(0,{timestamp:200,visibility:.05,coverage:.15,segmentation:.1}));assert.equal(good.retained,true);assert.equal(weak.ignored_for_aggregation,true);assert.equal(session.framesRetained,1);assert.equal(session.framesIgnored,1)});
test('one bad frame does not reset accumulated good evidence',()=>{const live=api(),session=live.createSession({startTime:0});fill(session,6);const before=session.landmarks.left_shoulder.observations.length;live.addFrame(session,frame(0,{visibility:.01,coverage:.1,segmentation:.1,timestamp:1500}));assert.equal(session.landmarks.left_shoulder.observations.length,before)});
test('mediocre frame can contribute independently usable landmarks',()=>{const live=api(),session=live.createSession({startTime:0,minimumUsableLandmarks:8});const input=frame(0,{visibility:.3,coverage:.4,segmentation:.35,timestamp:100});input.rawPose.landmarks.left_shoulder.visibility=.95;input.rawPose.landmarks.left_shoulder.presence=.95;const scored=live.addFrame(session,input);assert.equal(session.landmarks.left_shoulder.observations.length,1);assert.equal(session.landmarks.left_ankle.observations.length,0);assert.ok(scored.landmark_quality.left_shoulder.usable)});
test('temporal median rejects outliers',()=>{const live=api(),observations=[0,.001,-.001,.002,0,.25].map((x,index)=>({x_body_norm:.5+x,y_body_norm:.4+x,confidence:.9,quality:.9,timestamp:index})),result=live.stabilizeLandmark(observations,{minimumObservations:4});assert.ok(Math.abs(result.stabilized_position.x_body_norm-.5)<.005);assert.equal(result.outlier_count,1)});
test('jitter lowers stability while stable observations score high',()=>{const live=api(),stable=Array.from({length:8},(_,i)=>({x_body_norm:.5+(i%2)*.001,y_body_norm:.4,confidence:.9})),jitter=Array.from({length:8},(_,i)=>({x_body_norm:.45+i*.015,y_body_norm:.35+(i%3)*.02,confidence:.9}));const a=live.stabilizeLandmark(stable),b=live.stabilizeLandmark(jitter);assert.ok(a.stability_score>.9);assert.ok(b.stability_score<a.stability_score)});
test('body coordinates aggregate across image size changes',()=>{const live=api(),session=live.createSession({startTime:0});live.addFrame(session,frame(0,{width:200,height:400,timestamp:0}));live.addFrame(session,frame(0,{width:600,height:1200,timestamp:200}));const values=session.landmarks.left_elbow.observations;assert.equal(values.length,2);assert.ok(Math.abs(values[0].x_body_norm-values[1].x_body_norm)<1e-9);assert.notEqual(values[0].x_px,values[1].x_px)});
test('rolling frame and landmark buffers remain bounded',()=>{const live=api(),session=live.createSession({startTime:0,maxFrames:5,maxObservationsPerLandmark:7});fill(session,30);assert.ok(session.frameBuffer.length<=5);assert.ok(session.landmarks.left_shoulder.observations.length<=7);assert.ok(session.frameQualityHistory.length<=15)});
test('sessions classify sufficient, insufficient, and fallback',()=>{const live=api(),sufficient=live.createSession({startTime:0,minimumRetainedFrames:5,minimumObservations:4,minimumDurationMs:500});fill(sufficient,8);assert.equal(live.summarize(sufficient,1600).session.status,'sufficient');const insufficient=live.createSession({startTime:0,minimumRetainedFrames:5,minimumDurationMs:3000});fill(insufficient,2);assert.equal(live.summarize(insufficient,400).session.status,'insufficient');const fallback=live.createSession({startTime:0,minimumRetainedFrames:5,timeoutMs:1000});fill(fallback,2,{visibility:.1,coverage:.2,segmentation:.2});assert.equal(live.summarize(fallback,1500).session.status,'fallback_to_photo_mode')});
test('explicit fallback request produces fallback state',()=>{const live=api(),session=live.createSession({startTime:0});assert.equal(live.summarize(session,500,true).session.status,'fallback_to_photo_mode')});
test('debug summary contains no measurements',()=>{const live=api(),session=live.createSession({startTime:0});fill(session,6);const summary=live.summarize(session,2000);assert.equal(summary.measurements,null);assert.equal('circumferences' in summary,false);assert.ok(summary.landmarks.left_shoulder.observations.length<=session.config.maxObservationsPerLandmark)});
