const assert=require('node:assert/strict'),fs=require('node:fs'),test=require('node:test'),vm=require('node:vm');
function api(){const c={};for(const f of ['landmark-model.js','stage2-resolver.js','torso-profile.js','stage3-resolver.js','stage3b-validator.js','stage3c-refiner.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),c);return c}
function acromionFixture(scale=1,{slope=0,span=24,abduction=0,noise=false}={}){const a=api(),W=120*scale,H=180*scale,data=new Float32Array(W*H),fill=(l,r,t,b)=>{for(let y=Math.round(t*scale);y<=Math.round(b*scale);y++)for(let x=Math.round(l*scale);x<=Math.round(r*scale);x++)data[y*W+x]=.95};fill(48,72,20,28);fill(42,78,29,31);fill(34,86,32,35);fill(38,82,36,90);fill(28,36,34,105);fill(84,92,34,105);if(noise)for(let y=30;y<45;y+=3)data[Math.round(y*scale)*W+Math.round(33*scale)]=.95;const component=a.tailorScanStage2.dominantComponent({width:W,height:H,data}),p=(x,y,v=.9)=>({x:x/W,y:y/H,visibility:v,presence:v}),leftX=60-span/2,rightX=60+span/2,raw=a.tailorScanLandmarks.createRawPoseLandmarks({image_width:W,image_height:H,landmarks:{left_shoulder:p(leftX*scale,(34+slope)*scale),right_shoulder:p(rightX*scale,34*scale),left_elbow:p((30-abduction)*scale,70*scale),right_elbow:p((90+abduction)*scale,70*scale)}}),axis={top:{x:60*scale,y:10*scale},bottom:{x:60*scale,y:170*scale}};return{a,raw,component,axis,left:{x:leftX*scale,y:(34+slope)*scale,confidence:.9},right:{x:rightX*scale,y:34*scale,confidence:.9}}}
function profile(widths,start=34,step=4,extra={}){return{samples:widths.map((w,i)=>({body_y:start+i*step,width_px:w,smoothed_width_px:w,confidence:.9,left_boundary:{x:60-w/2,y:start+i*step},right_boundary:{x:60+w/2,y:start+i*step},center_x:60,...extra}))}}
function waistContext(widths,extra={}){const a=api(),W=120,H=180,p=(x,y)=>({x:x/W,y:y/H,visibility:.9,presence:.9}),raw=a.tailorScanLandmarks.createRawPoseLandmarks({image_width:W,image_height:H,landmarks:{left_shoulder:p(45,32),right_shoulder:p(75,34),left_hip:p(50,112),right_hip:p(70,112)}});return{a,raw,stage3b:{resolvedLandmarks:{left_outer_hip:null,right_outer_hip:null}},profile:profile(widths,36,4,extra)}}

test('acromion uses upper-arm projection and rejects strong curvature deep on the arm',()=>{const f=acromionFixture(),r=f.a.tailorScanStage3.resolveAcromionAnalysis({rawShoulder:f.left,oppositeShoulder:f.right,rawElbow:{x:30,y:70},component:f.component,rawPose:f.raw,bodyAxis:f.axis,side:'left'});assert.ok(r.point);assert.ok(r.diagnostics.projection_on_upper_arm_axis<=.3);assert.ok(r.diagnostics.rejected_candidates.every(c=>c.y_px<=f.left.y+Math.min(24*.34,Math.hypot(18,36)*.22)+1))});
test('acromion generalizes across scale, shoulder width, slope, and arm abduction',()=>{for(const [scale,options] of [[1,{span:18,slope:0}],[2,{span:34,slope:4}],[1,{span:26,slope:3,abduction:8,noise:true}]]){const f=acromionFixture(scale,options),r=f.a.tailorScanStage3.resolveAcromionAnalysis({rawShoulder:f.left,oppositeShoulder:f.right,rawElbow:{x:(30-(options.abduction||0))*scale,y:70*scale},component:f.component,rawPose:f.raw,bodyAxis:f.axis,side:'left'});assert.ok(r.point||r.diagnostics.confidence===0);if(r.point){assert.ok(r.point.x<f.left.x);assert.ok(r.diagnostics.vertical_displacement_as_fraction_of_shoulder_span<.5)}}});
test('ambiguous acromion competition lowers confidence',()=>{const f=acromionFixture(1,{noise:true}),r=f.a.tailorScanStage3.resolveAcromionAnalysis({rawShoulder:f.left,oppositeShoulder:f.right,rawElbow:{x:30,y:70},component:f.component,rawPose:f.raw,bodyAxis:f.axis,side:'left'});assert.ok(r.point);assert.ok(r.diagnostics.candidate_margin>=0&&r.diagnostics.candidate_margin<=1);assert.ok(r.point.confidence<=.9)});

test('sustained hourglass basin is accepted and separated from geometric minimum',()=>{const c=waistContext([46,45,43,40,37,34,33,33,34,37,41,45,48,50,51,52]),r=c.a.tailorScanStage3C.analyzeWaistZones({profile:c.profile,rawPose:c.raw,stage3b:c.stage3b});assert.ok(r.best_geometric_narrowing);assert.ok(r.accepted_anatomical_waist);assert.ok(r.accepted_anatomical_waist.waist_zone_end>=r.accepted_anatomical_waist.waist_zone_start)});
test('straight, V-shaped, broad-abdomen, and weak-indentation torsos remain unresolved',()=>{for(const widths of [Array(16).fill(42),[52,50,48,46,44,42,40,39,38,37,36,35,34,33,32,31],[40,41,43,46,49,52,54,55,55,54,53,52,51,50,49,48],[45,44,43,42,41,40,39,40,41,42,43,44,45,46,47,48]]){const c=waistContext(widths),r=c.a.tailorScanStage3C.analyzeWaistZones({profile:c.profile,rawPose:c.raw,stage3b:c.stage3b});assert.equal(r.accepted_anatomical_waist,null)}});
test('broad/narrow pelvis, asymmetry proxy, noise, clothing false narrowing, and multiple minima are handled conservatively',()=>{const shapes=[[48,46,43,39,35,34,35,39,44,50,56,60,62,63,64,65],[42,41,39,36,33,32,33,36,39,41,42,43,44,44,45,45],[48,46,40,35,34,35,41,44,39,34,33,35,42,48,52,54]];for(const widths of shapes){const c=waistContext(widths),r=c.a.tailorScanStage3C.analyzeWaistZones({profile:c.profile,rawPose:c.raw,stage3b:c.stage3b});assert.ok(Array.isArray(r.candidate_ranking));if(r.accepted_anatomical_waist)assert.ok(r.accepted_anatomical_waist.final_score>=.58)}const clothing=waistContext([46,45,44,30,44,43,42,41,42,44,46,48,50,52,54,55],{width_px:30,smoothed_width_px:44}),r=clothing.a.tailorScanStage3C.analyzeWaistZones({profile:clothing.profile,rawPose:clothing.raw,stage3b:clothing.stage3b});assert.equal(r.accepted_anatomical_waist,null)});
