const assert = require('node:assert/strict');
const fs = require('node:fs');
const test = require('node:test');
const vm = require('node:vm');
function api() { const c = {}; for (const f of ['landmark-model.js','stage2-resolver.js','torso-profile.js','stage3-resolver.js']) vm.runInNewContext(fs.readFileSync(f,'utf8'),c); return c; }
const W=100,H=160;
function mask(options={}) { const data=new Float32Array(W*H), fill=(l,r,t,b)=>{for(let y=t;y<=b;y++)for(let x=l;x<=r;x++)data[y*W+x]=.95}; fill(45,55,5,20); fill(47,53,21,27); fill(38,62,28,29); fill(32,68,30,32); fill(28,72,33,35); fill(32,68,36,55); fill(35,65,56,68); fill(38,62,69,80); fill(35,65,81,92); fill(29,71,93,108); if(options.obstructCrotch)fill(33,67,109,135);else{fill(33,45,109,150);fill(55,67,109,150)} fill(28,46,151,154);fill(54,72,151,154); if(options.arms!==false){fill(17,24,34,82);fill(76,83,34,82)} if(options.singleHole){for(let x=47;x<=53;x++)data[112*W+x]=0;fill(46,54,113,135)} if(options.noisy){for(let y=30;y<50;y+=3)data[y*W+27]=.95} return {width:W,height:H,data}; }
const p=(x,y,v=.9)=>({x:x/W,y:y/H,z:-.1,visibility:v,presence:v});
function pose(model, overrides={}) { return model.createRawPoseLandmarks({image_width:W,image_height:H,frame_id:'f',view_id:'front',landmarks:{nose:p(50,14),left_eye:p(47,12),right_eye:p(53,12),left_ear:p(44,15),right_ear:p(56,15),left_shoulder:p(40,33),right_shoulder:p(60,34),left_elbow:p(20,55),right_elbow:p(80,56),left_wrist:p(20,78),right_wrist:p(80,79),left_hip:p(42,96),right_hip:p(58,96),left_knee:p(39,130),right_knee:p(61,130),left_ankle:p(39,149),right_ankle:p(61,149),left_heel:p(36,153),right_heel:p(58,153),left_foot_index:p(45,154),right_foot_index:p(69,154),...overrides}}); }
function setup(options={}){const a=api(),raw=pose(a.tailorScanLandmarks,options.pose),m=mask(options.mask),component=a.tailorScanStage2.dominantComponent(m),stage2=a.tailorScanStage2.resolve({rawPose:raw,personMask:m});return{...a,raw,m,component,stage2}}

test('acromions resolve independently at contour transitions without forced symmetry',()=>{const s=setup(),ls={x:40,y:33,confidence:.9},rs={x:60,y:34,confidence:.9},left=s.tailorScanStage3.resolveAcromion({rawShoulder:ls,oppositeShoulder:rs,component:s.component,rawPose:s.raw,side:'left'}),right=s.tailorScanStage3.resolveAcromion({rawShoulder:rs,oppositeShoulder:ls,component:s.component,rawPose:s.raw,side:'right'});assert.ok(left.x<ls.x);assert.ok(right.x>rs.x);assert.notEqual(left.diagnostics.raw_shoulder.y,right.diagnostics.raw_shoulder.y);assert.ok(left.diagnostics.contour_candidate_count>0)});
test('acromion handles noisy contour and missing shoulder evidence',()=>{const s=setup({mask:{noisy:true}}),result=s.tailorScanStage3.resolveAcromion({rawShoulder:{x:40,y:33,confidence:.8},oppositeShoulder:{x:60,y:34,confidence:.8},component:s.component,rawPose:s.raw,side:'left'});assert.ok(result);assert.equal(s.tailorScanStage3.resolveAcromion({rawShoulder:null,oppositeShoulder:{x:60,y:34},component:s.component,rawPose:s.raw,side:'left'}),null)});
test('neck base uses bilateral neck expansion and tolerates one weaker side shape',()=>{const s=setup(),neck=s.tailorScanStage3.resolveNeckBase({component:s.component,rawPose:s.raw,bodyAxis:s.stage2.bodyAxis});assert.ok(neck);assert.ok(neck.left_transition.x<neck.x);assert.ok(neck.right_transition.x>neck.x);const weak=mask();for(let y=21;y<28;y++)weak.data[y*W+47]=0;const component=s.tailorScanStage2.dominantComponent(weak),oneSide=s.tailorScanStage3.resolveNeckBase({component,rawPose:s.raw,bodyAxis:s.stage2.bodyAxis});assert.ok(oneSide===null||oneSide.confidence<=neck.confidence)});
test('neck base is unresolved without shoulder evidence',()=>{const s=setup();s.raw.landmarks.left_shoulder=null;assert.equal(s.tailorScanStage3.resolveNeckBase({component:s.component,rawPose:s.raw,bodyAxis:s.stage2.bodyAxis}),null)});
test('torso profile follows center run, excludes detached arms, and retains raw widths',()=>{const s=setup(),profile=s.tailorScanTorsoProfile.buildTorsoWidthProfile({component:s.component,bodyAxis:s.stage2.bodyAxis,rawPose:s.raw,startY:40,endY:105});assert.equal(profile.samples.length,profile.unsmoothed_widths_px.length);const at60=profile.samples.find(x=>Math.round(x.body_y)===60);assert.ok(at60.left_boundary.x>24);assert.ok(at60.right_boundary.x<76)});
test('torso profile remains valid with noise and tilted axis',()=>{const s=setup({mask:{noisy:true}}),axis={top:{x:46,y:5},bottom:{x:54,y:154}},profile=s.tailorScanTorsoProfile.buildTorsoWidthProfile({component:s.component,bodyAxis:axis,rawPose:s.raw,startY:40,endY:100});assert.ok(profile.samples.filter(x=>x.width_px).length>40)});
function sample(y,w,score=.9){return{body_y:y,width_px:w,smoothed_width_px:w,confidence:score,left_boundary:{x:50-w/2,y},right_boundary:{x:50+w/2,y},center_x:50}}
test('waist selects clear local narrowing among multiple minima',()=>{const s=api(),profile={samples:[sample(40,40),sample(45,38),sample(50,34),sample(55,38),sample(60,39),sample(65,36),sample(70,30),sample(75,36),sample(80,40)]},r=s.tailorScanStage3.selectWaist(profile,35,85);assert.equal(r.point.body_y,70);assert.ok(r.candidates.length>1)});
test('waist returns unresolved when no meaningful narrowing exists',()=>{const s=api(),profile={samples:Array.from({length:12},(_,i)=>sample(40+i*3,40))},r=s.tailorScanStage3.selectWaist(profile,35,80);assert.equal(r.point,null);assert.equal(r.warning,'WAIST_UNRESOLVED')});
test('waist smoothing avoids a single clothing-like false edge',()=>{const s=api(),profile={samples:[40,40,40,24,40,40,38,32,38,40].map((w,i)=>sample(40+i*4,w))};profile.samples[3].smoothed_width_px=38;const r=s.tailorScanStage3.selectWaist(profile,35,85);assert.notEqual(r.point?.body_y,52)});
test('hip selects broad pelvis and rejects upper-thigh false maximum',()=>{const s=api(),profile={samples:[sample(88,42),sample(92,44),sample(96,46),sample(100,45),sample(106,52),sample(112,35)]},r=s.tailorScanStage3.selectHip(profile,96,130);assert.ok(r.point.body_y<=100)});
test('hip reports ambiguous clothing through full resolver warning when torso run is broad',()=>{const s=setup(),r=s.tailorScanStage3.resolve({rawPose:s.raw,personMask:s.m,stage2:s.stage2});assert.ok(r.resolvedLandmarks.left_outer_hip||r.warnings.includes('HIP_UNRESOLVED'));assert.ok(Array.isArray(r.warnings))});
test('crotch resolves persistent two-leg separation',()=>{const s=setup(),r=s.tailorScanStage3.resolveCrotch({component:s.component,rawPose:s.raw,bodyAxis:s.stage2.bodyAxis});assert.ok(r);assert.ok(r.y>=108&&r.y<=112)});
test('crotch ignores a one-row segmentation hole',()=>{const s=setup({mask:{singleHole:true,obstructCrotch:true}}),r=s.tailorScanStage3.resolveCrotch({component:s.component,rawPose:s.raw,bodyAxis:s.stage2.bodyAxis});assert.equal(r,null)});
test('crotch remains unresolved under clothing obstruction',()=>{const s=setup({mask:{obstructCrotch:true}}),r=s.tailorScanStage3.resolveCrotch({component:s.component,rawPose:s.raw,bodyAxis:s.stage2.bodyAxis});assert.equal(r,null)});
test('full Stage 3 keeps raw pose unchanged and failures do not crash other landmarks',()=>{const s=setup(),before=JSON.stringify(s.raw.landmarks),r=s.tailorScanStage3.resolve({rawPose:s.raw,personMask:s.m,stage2:s.stage2});assert.equal(JSON.stringify(s.raw.landmarks),before);assert.ok(r.resolvedLandmarks.left_acromion);assert.equal(r.resolvedLandmarks.left_acromion.source,'refined');assert.ok(r.confidence.left_acromion.category)});
