const assert=require('node:assert/strict'),fs=require('node:fs'),test=require('node:test'),vm=require('node:vm');
function api(){const c={};for(const f of ['landmark-model.js','stage2-resolver.js','torso-profile.js','stage3-resolver.js','stage3b-validator.js'])vm.runInNewContext(fs.readFileSync(f,'utf8'),c);return c}
const W=100,H=160,p=(x,y,v=.9)=>({x:x/W,y:y/H,visibility:v,presence:v});
function raw(model){return model.createRawPoseLandmarks({image_width:W,image_height:H,landmarks:{left_shoulder:p(40,34),right_shoulder:p(60,36),left_hip:p(42,96),right_hip:p(58,96),left_knee:p(40,132),right_knee:p(60,132)}})}
const axis={top:{x:50,y:5},bottom:{x:50,y:155}};
function landmark(model,name,x,y,confidence=.9,source='refined',diagnostics={}){return model.createLandmark({name,x_px:x,y_px:y,x_norm:x/W,y_norm:y/H,x_body_norm:.5+(x-50)/150,y_body_norm:(y-5)/150,confidence,source,diagnostics})}
function sample(y,w,extra={}){return{body_y:y,width_px:w,smoothed_width_px:w,confidence:.9,left_boundary:{x:50-w/2,y},right_boundary:{x:50+w/2,y},center_x:50,...extra}}

test('acromion rejects centerline crossing and excessive shoulder-relative displacement',()=>{const a=api(),r=raw(a.tailorScanLandmarks),cross=a.tailorScanStage3B.validateAcromion({point:landmark(a.tailorScanLandmarks,'left_acromion',70,35),rawShoulder:{x:40,y:34},oppositeShoulder:{x:60,y:36},bodyAxis:axis,side:'left'});assert.equal(cross.point,null);assert.ok(cross.warnings.includes('ACROMION_SIDE_CROSSING_REJECTED'));const far=a.tailorScanStage3B.validateAcromion({point:landmark(a.tailorScanLandmarks,'left_acromion',20,35),rawShoulder:{x:40,y:34},oppositeShoulder:{x:60,y:36},bodyAxis:axis,side:'left'});assert.equal(far.point,null);assert.ok(far.warnings.includes('ACROMION_EXCESSIVE_DISPLACEMENT'))});
test('correct outward acromions are accepted independently without forcing symmetry',()=>{const a=api(),left=a.tailorScanStage3B.validateAcromion({point:landmark(a.tailorScanLandmarks,'left_acromion',32,32),rawShoulder:{x:40,y:34},oppositeShoulder:{x:60,y:36},bodyAxis:axis,side:'left'}),right=a.tailorScanStage3B.validateAcromion({point:landmark(a.tailorScanLandmarks,'right_acromion',68,39),rawShoulder:{x:60,y:36},oppositeShoulder:{x:40,y:34},bodyAxis:axis,side:'right'});assert.ok(left.point&&right.point);assert.notEqual(left.point.y_px,right.point.y_px)});
test('neck must be medial, narrower than shoulders, and distinct from acromions',()=>{const a=api(),m=a.tailorScanLandmarks,left=landmark(m,'left_acromion',30,34),right=landmark(m,'right_acromion',70,35),good=landmark(m,'neck_base',50,28,.8,'derived',{left_neck_transition:{x:44,y:28},right_neck_transition:{x:56,y:28},expansion_strength:.4}),accepted=a.tailorScanStage3B.validateNeck({point:good,leftAcromion:left,rightAcromion:right,bodyAxis:axis});assert.ok(accepted.point);const wide=landmark(m,'neck_base',50,30,.9,'derived',{left_neck_transition:{x:25,y:30},right_neck_transition:{x:75,y:30}});assert.equal(a.tailorScanStage3B.validateNeck({point:wide,leftAcromion:left,rightAcromion:right,bodyAxis:axis}).point,null);const collision=landmark(m,'neck_base',50,34,.9,'derived',{left_neck_transition:{x:30,y:34},right_neck_transition:{x:60,y:34}});assert.equal(a.tailorScanStage3B.validateNeck({point:collision,leftAcromion:left,rightAcromion:right,bodyAxis:axis}).point,null)});
test('strong stable waist is accepted while weak and out-of-interval minima are unresolved',()=>{const a=api(),r=raw(a.tailorScanLandmarks),strong={torsoWidthProfile:{samples:[sample(40,40),sample(45,39),sample(50,38),sample(55,36),sample(60,32),sample(65,36),sample(70,39),sample(80,42),sample(90,44)]}},accepted=a.tailorScanStage3B.refineWaist({stage3:strong,rawPose:r});assert.ok(accepted.accepted);const weak={torsoWidthProfile:{samples:Array.from({length:12},(_,i)=>sample(40+i*4,40))}};assert.equal(a.tailorScanStage3B.refineWaist({stage3:weak,rawPose:r}).accepted,null);const outside={torsoWidthProfile:{samples:[sample(20,20),sample(25,40),sample(30,42),...weak.torsoWidthProfile.samples]}};assert.notEqual(a.tailorScanStage3B.refineWaist({stage3:outside,rawPose:r}).accepted?.body_y,20)});
test('clothing and arm distortion prevent waist acceptance',()=>{const a=api(),r=raw(a.tailorScanLandmarks),profile={torsoWidthProfile:{samples:[sample(45,40),sample(50,39),sample(55,36),sample(60,30,{width_px:20,arm_separation_ambiguous:true}),sample(65,36),sample(70,39),sample(75,40)]}},result=a.tailorScanStage3B.refineWaist({stage3:profile,rawPose:r});assert.equal(result.accepted,null);assert.ok(result.warnings.includes('WAIST_ARM_INTERFERENCE'))});
test('visible separation confidence is independent from anatomical crotch confidence',()=>{const a=api(),m=a.tailorScanLandmarks,r=raw(m),visible=landmark(m,'crotch_center',50,112,.92,'derived',{axis_agreement:.95,persistence_rows:4}),stage3={resolvedLandmarks:{crotch_center:visible}},result=a.tailorScanStage3B.refineCrotch({stage3,rawPose:r});assert.ok(result.visible);assert.ok(result.analysis.visible_separation_confidence>result.analysis.anatomical_crotch_confidence);assert.equal(result.crotch,null);assert.ok(result.warnings.includes('CROTCH_CLOTHING_OBSTRUCTION'))});
test('crotch can remain resolved when early persistent evidence is anatomically plausible',()=>{const a=api(),m=a.tailorScanLandmarks,r=raw(m),visible=landmark(m,'crotch_center',50,103,.95,'derived',{axis_agreement:.98,persistence_rows:4}),result=a.tailorScanStage3B.refineCrotch({stage3:{resolvedLandmarks:{crotch_center:visible}},rawPose:r});assert.ok(result.visible);assert.ok(result.crotch)});
test('outer hip survives waist failure and ordering invariants reject impossible landmarks',()=>{const a=api(),m=a.tailorScanLandmarks,r=raw(m),values={left_outer_hip:landmark(m,'left_outer_hip',30,92,.8,'silhouette'),right_outer_hip:landmark(m,'right_outer_hip',70,92,.8,'silhouette'),natural_waist_center:landmark(m,'natural_waist_center',50,100,.8,'derived'),left_waist_boundary:landmark(m,'left_waist_boundary',35,100,.8,'silhouette'),right_waist_boundary:landmark(m,'right_waist_boundary',65,100,.8,'silhouette')},result=a.tailorScanStage3B.validateInvariants({values,rawPose:r,bodyAxis:axis});assert.equal(values.natural_waist_center,null);assert.ok(values.left_outer_hip);assert.ok(result.warnings.includes('WAIST_ANATOMICAL_ORDER_INVALID'))});
test('numeric invariants reject NaN and confidence remains bounded',()=>{const a=api(),m=a.tailorScanLandmarks,r=raw(m),values={left_outer_hip:{...landmark(m,'left_outer_hip',30,92,.8,'silhouette'),x_px:NaN},right_outer_hip:landmark(m,'right_outer_hip',70,92,1,'silhouette')},result=a.tailorScanStage3B.validateInvariants({values,rawPose:r,bodyAxis:axis});assert.equal(values.left_outer_hip,null);assert.equal(values.right_outer_hip.confidence,1);assert.ok(result.rejections.length)});
